package Semana3;

import Semana3.Modelo;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.Locale;

/**
 *
 * @author georg
 */
public class VentanaAplicacion2 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public VentanaAplicacion2(String title) {
        super(title);
        modelo = new Modelo();
        initComponents();

        btnLibras.setText("Kg \u2192 lb");
        btnKilos.setText("lb \u2192 Kg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        etqKilos = new javax.swing.JLabel();
        campoKilos = new javax.swing.JTextField();
        etqLibras = new javax.swing.JLabel();
        campoLibras = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        panelBotones = new javax.swing.JPanel();
        btnLibras = new javax.swing.JButton();
        btnKilos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(320, 240));
        setPreferredSize(new java.awt.Dimension(320, 240));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        etqKilos.setText("Kilos :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 4, 4);
        getContentPane().add(etqKilos, gridBagConstraints);

        campoKilos.setText("0.0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 4, 8);
        getContentPane().add(campoKilos, gridBagConstraints);

        etqLibras.setText("Libras :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 4, 4);
        getContentPane().add(etqLibras, gridBagConstraints);

        campoLibras.setText("0.0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 4, 8);
        getContentPane().add(campoLibras, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(filler1, gridBagConstraints);

        btnLibras.setText("Kg -> lb");
        btnLibras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertirKilos(evt);
            }
        });
        panelBotones.add(btnLibras);

        btnKilos.setText("lb -> Kg");
        btnKilos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertirLibras(evt);
            }
        });
        panelBotones.add(btnKilos);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(panelBotones, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void convertirKilos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertirKilos
        double kilos;
        try {
            kilos = FMT.parse(campoKilos.getText()).doubleValue();
            modelo.fijarKilos(kilos);
        } catch (ParseException ex) {
        }

        actualizarCampos();
        campoKilos.requestFocusInWindow();
        campoKilos.selectAll();
    }//GEN-LAST:event_convertirKilos

    private void convertirLibras(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertirLibras
        double libras;
        try {
            libras = FMT.parse(campoLibras.getText()).doubleValue();
            modelo.fijarLibras(libras);
        } catch (ParseException ex) {
        }

        actualizarCampos();
        campoLibras.requestFocusInWindow();
        campoLibras.selectAll();
    }//GEN-LAST:event_convertirLibras

    // <editor-fold defaultstate="collapsed" desc="Custom Code">
    public void init() {
        setLocationRelativeTo(null);
        setVisible(true);

        actualizarCampos();
        campoKilos.selectAll();
    }

    public Modelo obtenerModelo() {
        return modelo;
    }

    public void actualizarCampos() {
        campoKilos.setText(String.format("%4.1f", modelo.kilos()));
        campoLibras.setText(String.format("%4.1f", modelo.libras()));
    }
    // </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAplicacion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAplicacion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAplicacion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAplicacion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VentanaAplicacion2(null).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKilos;
    private javax.swing.JButton btnLibras;
    private javax.swing.JTextField campoKilos;
    private javax.swing.JTextField campoLibras;
    private javax.swing.JLabel etqKilos;
    private javax.swing.JLabel etqLibras;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel panelBotones;
    // End of variables declaration//GEN-END:variables

    // <editor-fold defaultstate="collapsed" desc="Custom Variables">
    private static final Locale LOC = new Locale.Builder()
            .setLanguage("es")
            .setRegion("CR")
            .build();
    private static final DecimalFormat FMT
            = (DecimalFormat) NumberFormat.getNumberInstance(LOC);
    private final Modelo modelo;
    // </editor-fold>
}